/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace SmartLandRegistry {
      
    export type TransferStruct = {transferId: BytesLike, parcelId: BytesLike, from: AddressLike, to: AddressLike, nonce: BigNumberish, deadline: BigNumberish, metadataHash: BytesLike}

    export type TransferStructOutput = [transferId: string, parcelId: string, from: string, to: string, nonce: bigint, deadline: bigint, metadataHash: string] & {transferId: string, parcelId: string, from: string, to: string, nonce: bigint, deadline: bigint, metadataHash: string }
  
    }

  export interface SmartLandRegistryInterface extends Interface {
    getFunction(nameOrSignature: "APPROVER_ROLE" | "DEFAULT_ADMIN_ROLE" | "NAME" | "REGISTRAR_ROLE" | "VERSION" | "approvalThreshold" | "executeTransfer" | "getRoleAdmin" | "grantRole" | "hasRole" | "ownerOf" | "parcelExists" | "parcelNonce" | "registerParcel" | "renounceRole" | "revokeRole" | "setApprovalThreshold" | "supportsInterface" | "updateParcelMetadata"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApprovalThresholdUpdated" | "ParcelMetadataUpdated" | "ParcelRegistered" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "TransferExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'APPROVER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'NAME', values?: undefined): string;
encodeFunctionData(functionFragment: 'REGISTRAR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'approvalThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeTransfer', values: [SmartLandRegistry.TransferStruct, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'parcelExists', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'parcelNonce', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'registerParcel', values: [BytesLike, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setApprovalThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateParcelMetadata', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'APPROVER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'NAME', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'REGISTRAR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approvalThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'parcelExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'parcelNonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerParcel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateParcelMetadata', data: BytesLike): Result;
  }

  
    export namespace ApprovalThresholdUpdatedEvent {
      export type InputTuple = [threshold: BigNumberish];
      export type OutputTuple = [threshold: bigint];
      export interface OutputObject {threshold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ParcelMetadataUpdatedEvent {
      export type InputTuple = [parcelId: BytesLike, metadataHash: BytesLike];
      export type OutputTuple = [parcelId: string, metadataHash: string];
      export interface OutputObject {parcelId: string, metadataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ParcelRegisteredEvent {
      export type InputTuple = [parcelId: BytesLike, owner: AddressLike, metadataHash: BytesLike];
      export type OutputTuple = [parcelId: string, owner: string, metadataHash: string];
      export interface OutputObject {parcelId: string, owner: string, metadataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferExecutedEvent {
      export type InputTuple = [transferId: BytesLike, parcelId: BytesLike, from: AddressLike, to: AddressLike, nonce: BigNumberish, metadataHash: BytesLike];
      export type OutputTuple = [transferId: string, parcelId: string, from: string, to: string, nonce: bigint, metadataHash: string];
      export interface OutputObject {transferId: string, parcelId: string, from: string, to: string, nonce: bigint, metadataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SmartLandRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): SmartLandRegistry;
    waitForDeployment(): Promise<this>;

    interface: SmartLandRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    APPROVER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    NAME: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    REGISTRAR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    approvalThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    executeTransfer: TypedContractMethod<
      [t: SmartLandRegistry.TransferStruct, signatures: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [parcelId: BytesLike, ],
      [string],
      'view'
    >
    

    
    parcelExists: TypedContractMethod<
      [parcelId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    parcelNonce: TypedContractMethod<
      [parcelId: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    registerParcel: TypedContractMethod<
      [parcelId: BytesLike, owner: AddressLike, metadataHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalThreshold: TypedContractMethod<
      [threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    updateParcelMetadata: TypedContractMethod<
      [parcelId: BytesLike, metadataHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'APPROVER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'NAME'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'REGISTRAR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'approvalThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'executeTransfer'): TypedContractMethod<
      [t: SmartLandRegistry.TransferStruct, signatures: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [parcelId: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'parcelExists'): TypedContractMethod<
      [parcelId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'parcelNonce'): TypedContractMethod<
      [parcelId: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerParcel'): TypedContractMethod<
      [parcelId: BytesLike, owner: AddressLike, metadataHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalThreshold'): TypedContractMethod<
      [threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'updateParcelMetadata'): TypedContractMethod<
      [parcelId: BytesLike, metadataHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ApprovalThresholdUpdated'): TypedContractEvent<ApprovalThresholdUpdatedEvent.InputTuple, ApprovalThresholdUpdatedEvent.OutputTuple, ApprovalThresholdUpdatedEvent.OutputObject>;
getEvent(key: 'ParcelMetadataUpdated'): TypedContractEvent<ParcelMetadataUpdatedEvent.InputTuple, ParcelMetadataUpdatedEvent.OutputTuple, ParcelMetadataUpdatedEvent.OutputObject>;
getEvent(key: 'ParcelRegistered'): TypedContractEvent<ParcelRegisteredEvent.InputTuple, ParcelRegisteredEvent.OutputTuple, ParcelRegisteredEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'TransferExecuted'): TypedContractEvent<TransferExecutedEvent.InputTuple, TransferExecutedEvent.OutputTuple, TransferExecutedEvent.OutputObject>;

    filters: {
      
      'ApprovalThresholdUpdated(uint256)': TypedContractEvent<ApprovalThresholdUpdatedEvent.InputTuple, ApprovalThresholdUpdatedEvent.OutputTuple, ApprovalThresholdUpdatedEvent.OutputObject>;
      ApprovalThresholdUpdated: TypedContractEvent<ApprovalThresholdUpdatedEvent.InputTuple, ApprovalThresholdUpdatedEvent.OutputTuple, ApprovalThresholdUpdatedEvent.OutputObject>;
    

      'ParcelMetadataUpdated(bytes32,bytes32)': TypedContractEvent<ParcelMetadataUpdatedEvent.InputTuple, ParcelMetadataUpdatedEvent.OutputTuple, ParcelMetadataUpdatedEvent.OutputObject>;
      ParcelMetadataUpdated: TypedContractEvent<ParcelMetadataUpdatedEvent.InputTuple, ParcelMetadataUpdatedEvent.OutputTuple, ParcelMetadataUpdatedEvent.OutputObject>;
    

      'ParcelRegistered(bytes32,address,bytes32)': TypedContractEvent<ParcelRegisteredEvent.InputTuple, ParcelRegisteredEvent.OutputTuple, ParcelRegisteredEvent.OutputObject>;
      ParcelRegistered: TypedContractEvent<ParcelRegisteredEvent.InputTuple, ParcelRegisteredEvent.OutputTuple, ParcelRegisteredEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'TransferExecuted(bytes32,bytes32,address,address,uint256,bytes32)': TypedContractEvent<TransferExecutedEvent.InputTuple, TransferExecutedEvent.OutputTuple, TransferExecutedEvent.OutputObject>;
      TransferExecuted: TypedContractEvent<TransferExecutedEvent.InputTuple, TransferExecutedEvent.OutputTuple, TransferExecutedEvent.OutputObject>;
    
    };
  }